### ISSUE TITLE
add  single-layer solution sample

### ISSUE THREAD

**Issue by bxjg1987** [realLiangshiwei/Lsw.Abp.AntDesignUI#14]
abp7.1 Lsw.Abp.AntDesignUI 0.7.0
I tried, but encountered an error registering the script 'Blazor. Global' repeatedly

**Comment by realLiangshiwei** [comment]
Please share a minimal reproducible example

**Comment by realLiangshiwei** [comment]
https://github.com/realLiangshiwei/Lsw.Abp.AntDesignUI/issues/13
