### ISSUE TITLE
I created a solution using MySQL and PostgreSQL and encountered a problem

### ISSUE THREAD

**Issue by WhiteEnzuo** [realLiangshiwei/Lsw.Abp.AntDesignUI#21]
Hello, I used MySQL and PostgreSQL to create a solution, and then modified the code according to Readme. The following message appears
Error: invalid_ Scope
Error_ Description: The specified 'scope' is invalid
Error_ Uri: https://documentation.openiddict.com/errors/ID2052
There's no problem with using Sql Server

**Comment by realLiangshiwei** [comment]
This is not related to `Lsw.Abp.AntDesignUI`, it's just a UI theme.

**Comment by WhiteEnzuo** [comment]
Excuse me, what if I want to use MySQL or PgSQL

**Comment by realLiangshiwei** [comment]
**This is not related to Lsw.Abp.AntDesignUI**, please open an issue on the ABP repo.
