### ISSUE TITLE
AbpCrudPageBase HandleErrorAsync err.

### ISSUE THREAD

**Issue by pkingwsd** [realLiangshiwei/Lsw.Abp.AntDesignUI#24]
env: win10 WPF blazor hybird version:0.92

    protected override async Task HandleErrorAsync(Exception exception) **//crash**
    {
        await base.HandleErrorAsync(exception);
    }

//--------------------------------------------------------------------------------------------------------
    protected override async Task HandleErrorAsync(Exception exception) **//work**
    {
if (IsDisposed)
{
    return;
}

Logger.LogException(exception);
await InvokeAsync(async () =>
{
    await UserExceptionInformer.InformAsync(new UserExceptionInformerContext(exception));
    StateHasChanged();
});
    }

很神奇。

**Comment by realLiangshiwei** [comment]
你的ABP版本？
ABP这里已经改了
https://github.com/abpframework/abp/pull/17040

**Comment by pkingwsd** [comment]
8.0.0 rc3

**Comment by realLiangshiwei** [comment]
分享一个测试项目

**Comment by pkingwsd** [comment]
现在在项目中，后面给你发一个

**Comment by realLiangshiwei** [comment]
: )
