### ISSUE TITLE
  TableColumn Data Bug

### ISSUE THREAD

**Issue by pkingwsd** [realLiangshiwei/Lsw.Abp.AntDesignUI#25]
new TableColumn
 {
     Title = L["Parameters"],
     Data = string.Empty,  // 如果把它去掉了，就报错
     ValueConverter = data=>
     { 
         return data.As<AuditLogDto>().Actions?.FirstOrDefault()?.Parameters ?? string.Empty;
     }
 },

**Comment by realLiangshiwei** [comment]
异常信息是什么
