### ISSUE TITLE
AbpException: No theme registered! Use AbpThemingOptions to register themes.

### ISSUE THREAD

**Issue by horsewww** [realLiangshiwei/Lsw.Abp.AntDesignUI#27]
一个基于 ABP的Blazor Server项目，abp的版本是8.0.4.  按照引入了这个库之后，启动时浏览器上出现了异常：
```
AbpException: No theme registered! Use AbpThemingOptions to register themes.
Volo.Abp.AspNetCore.Mvc.UI.Theming.DefaultThemeSelector.GetCurrentThemeInfo()
```
堆栈如下：
Volo.Abp.AspNetCore.Mvc.UI.Theming.DefaultThemeSelector.GetCurrentThemeInfo()
Volo.Abp.AspNetCore.Mvc.UI.Theming.DefaultThemeManager.GetCurrentTheme()
Volo.Abp.AspNetCore.Mvc.UI.Theming.DefaultThemeManager.get_CurrentTheme()
AspNetCoreGeneratedDocument.Pages__ViewStart.ExecuteAsync()
Microsoft.AspNetCore.Mvc.Razor.RazorView.RenderPageCoreAsync(IRazorPage page, ViewContext context)
Microsoft.AspNetCore.Mvc.Razor.RazorView.RenderViewStartsAsync(ViewContext context)
Microsoft.AspNetCore.Mvc.Razor.RazorView.RenderPageAsync(IRazorPage page, ViewContext context, bool invokeViewStarts)
Microsoft.AspNetCore.Mvc.Razor.RazorView.RenderAsync(ViewContext context)
Microsoft.AspNetCore.Mvc.ViewFeatures.ViewExecutor.ExecuteAsync(ViewContext viewContext, string contentType, Nullable<int> statusCode)
Microsoft.AspNetCore.Mvc.ViewFeatures.ViewExecutor.ExecuteAsync(ViewContext viewContext, string contentType, Nullable<int> statusCode)
Microsoft.AspNetCore.Mvc.Infrastructure.ResourceInvoker.<InvokeNextResultFilterAsync>g__Awaited|30_0<TFilter, TFilterAsync>(ResourceInvoker invoker, Task lastTask, State next, Scope scope, object state, bool isCompleted)
Microsoft.AspNetCore.Mvc.Infrastructure.ResourceInvoker.Rethrow(ResultExecutedContextSealed context)
Microsoft.AspNetCore.Mvc.Infrastructure.ResourceInvoker.ResultNext<TFilter, TFilterAsync>(ref State next, ref Scope scope, ref object state, ref bool isCompleted)
Microsoft.AspNetCore.Mvc.Infrastructure.ResourceInvoker.InvokeResultFilters()
Microsoft.AspNetCore.Mvc.Infrastructure.ResourceInvoker.<InvokeNextResourceFilter>g__Awaited|25_0(ResourceInvoker invoker, Task lastTask, State next, Scope scope, object state, bool isCompleted)
Microsoft.AspNetCore.Mvc.Infrastructure.ResourceInvoker.Rethrow(ResourceExecutedContextSealed context)
Microsoft.AspNetCore.Mvc.Infrastructure.ResourceInvoker.Next(ref State next, ref Scope scope, ref object state, ref bool isCompleted)
Microsoft.AspNetCore.Mvc.Infrastructure.ResourceInvoker.InvokeFilterPipelineAsync()
Microsoft.AspNetCore.Mvc.Infrastructure.ResourceInvoker.<InvokeAsync>g__Logged|17_1(ResourceInvoker invoker)
Microsoft.AspNetCore.Mvc.Infrastructure.ResourceInvoker.<InvokeAsync>g__Logged|17_1(ResourceInvoker invoker)
Microsoft.AspNetCore.Routing.EndpointMiddleware.<Invoke>g__AwaitRequestTask|7_0(Endpoint endpoint, Task requestTask, ILogger logger)
Swashbuckle.AspNetCore.SwaggerUI.SwaggerUIMiddleware.Invoke(HttpContext httpContext)
Swashbuckle.AspNetCore.Swagger.SwaggerMiddleware.Invoke(HttpContext httpContext, ISwaggerProvider swaggerProvider)
Microsoft.AspNetCore.Authorization.AuthorizationMiddleware.Invoke(HttpContext context)
Volo.Abp.AspNetCore.Security.Claims.AbpDynamicClaimsMiddleware.InvokeAsync(HttpContext context, RequestDelegate next)

关键代码：
```
[DependsOn(
    typeof(CNAdminAbpApplicationModule),
    typeof(CNAdminAbpEntityFrameworkCoreModule),
    typeof(CNAdminAbpHttpApiModule),
    typeof(AbpAutofacModule),
    typeof(AbpSwashbuckleModule),
    typeof(AbpAspNetCoreSerilogModule),
    typeof(AbpAccountWebOpenIddictModule),
    typeof(AbpAspNetCoreComponentsServerAntDesignThemeModule),
    typeof(AbpAspNetCoreComponentsWebAntDesignThemeModule),  //注释这句结果不变
    typeof(AbpIdentityBlazorServerAntDesignModule),
    typeof(AbpTenantManagementBlazorServerAntDesignModule),
    typeof(AbpSettingManagementBlazorServerAntDesignModule)
   )]
public class AdminAbpBlazorModule : AbpModule

```

**Comment by keoy7am** [comment]
能否提供repo, 有點難還原問題

但推測是少了 ThemeModule 註冊
可以嘗試調整成下方範例

```
[DependsOn(
    typeof(CNAdminAbpApplicationModule),  
    typeof(CNAdminAbpEntityFrameworkCoreModule),  
    typeof(CNAdminAbpHttpApiModule),  
    typeof(AbpAspNetCoreMvcUiBasicThemeModule), // 加入這行試試
    typeof(AbpAutofacModule),
    typeof(AbpSwashbuckleModule),
    typeof(AbpAspNetCoreSerilogModule),
    typeof(AbpAccountWebOpenIddictModule),
    typeof(AbpAspNetCoreComponentsServerAntDesignThemeModule),
    // typeof(AbpAspNetCoreComponentsWebAntDesignThemeModule),  //注释这句结果不变
    typeof(AbpIdentityBlazorServerAntDesignModule),
    typeof(AbpTenantManagementBlazorServerAntDesignModule),
    typeof(AbpSettingManagementBlazorServerAntDesignModule)
   )]
public class AdminAbpBlazorModule : AbpModule
```

**Comment by keoy7am** [comment]
在 [Quick Start](https://github.com/realLiangshiwei/Lsw.Abp.AntDesignUI/tree/main?tab=readme-ov-file#quick-start) 中的使用說明
其實是 WebAssembly 的範例

但是在 Blazor Server 中
應該需要把你上方的
`typeof(AbpAspNetCoreComponentsWebAntDesignThemeModule)`
替換為
`typeof(AbpAspNetCoreComponentsServerAntDesignThemeModule)`

查看 [AbpAspNetCoreComponentsServerAntDesignThemeModule 源代碼](https://github.com/realLiangshiwei/Lsw.Abp.AntDesignUI/blob/main/modules/AntDesignTheme/Lsw.Abp.AspnetCore.Components.Server.AntDesignTheme/AbpAspNetCoreComponentsServerAntDesignThemeModule.cs)

裡面是針對 AbpBundlingOptions 及 AbpToolbarOptions 的 Theme 設定

但參考 [BookStoreBlazorModule](https://github.com/realLiangshiwei/Lsw.Abp.AntDesignUI/blob/main/samples/BookStore/src/BookStore.BlazorServer/BookStoreBlazorModule.cs)

不加入 `typeof(AbpAspNetCoreComponentsServerAntDesignThemeModule)` 理應也能運作

依照提問的問題

上方的[調整](https://github.com/realLiangshiwei/Lsw.Abp.AntDesignUI/issues/27#issuecomment-2028575961)應該就能正常運作了

**Comment by keoy7am** [comment]
抱歉, 剛沒有看到原本提供的代碼已有 AbpAspNetCoreComponentsServerAntDesignThemeModule 的引用了
但應不影響問題的修正
若仍發生請提供repo以便偵錯

**Comment by realLiangshiwei** [comment]
请提供复现示例

**Comment by xhanglizhu** [comment]
需要在BlazorModule.cs 里加上`typeof(AbpAspNetCoreMvcUiBasicThemeModule)`
