### ISSUE TITLE
示例中的登录界面和个人信息界面的主题和主界面不相同

### ISSUE THREAD

**Issue by horsewww** [realLiangshiwei/Lsw.Abp.AntDesignUI#28]
BookStore.BlazorServer 示例，登录界面和个人信息界面的主题是基本主题，不是AntDesign的。要如何修改才能让主题都用AntDesign的呢？
![image](https://github.com/realLiangshiwei/Lsw.Abp.AntDesignUI/assets/37998380/a3beeea5-d440-4623-afd5-202010744e72)
![image](https://github.com/realLiangshiwei/Lsw.Abp.AntDesignUI/assets/37998380/7880fd0b-8074-4384-ae1e-1631a1031599)

**Comment by realLiangshiwei** [comment]
用不了，这些都是MVC UI的部分，Blazor 使用的是授权码登陆流程

**Comment by xhanglizhu** [comment]
> 用不了，这些都是MVC UI的部分，Blazor 使用的是授权码登陆流程
@realLiangshiwei 
有哪些方法可以实现？ 增加个AccountManage AntDesignUI模块？

**Comment by realLiangshiwei** [comment]
你可以不使用MVC Account模块，自己实现一个Blazor Accon UI来使用password flow登陆
