### ISSUE TITLE
Could not find 'AntDesign.interop.modalHelper.focusDialog' ('AntDesign' was undefined)

### ISSUE THREAD

**Issue by DreamlessRaw** [realLiangshiwei/Lsw.Abp.AntDesignUI#3]
![image](https://user-images.githubusercontent.com/47837339/160099831-3fd41359-4aba-4236-b6a8-ff235b5289a5.png)
![image](https://user-images.githubusercontent.com/47837339/160099998-594f5440-ea2f-4c95-ba70-0c88795c0c01.png)
![image](https://user-images.githubusercontent.com/47837339/160100369-a1a81fb3-b2ea-4065-b7c6-a278de59f850.png)

网页无法加载

**Comment by realLiangshiwei** [comment]
怎么复现呢？
