### ISSUE TITLE
Is there any plan to update to 8.2.0?

### ISSUE THREAD

**Issue by thirking** [realLiangshiwei/Lsw.Abp.AntDesignUI#30]
Want to migrate to Full stack blazor，It's really great!

**Comment by qqzhw** [comment]
+1

**Comment by realLiangshiwei** [comment]
I will update this week

**Comment by realLiangshiwei** [comment]
https://github.com/realLiangshiwei/Lsw.Abp.AntDesignUI/commit/cbf1b7120c93be5e9823aa4e0067633f60454093
