### ISSUE TITLE
Create a webapp sample

### ISSUE THREAD

**Issue by realLiangshiwei** [realLiangshiwei/Lsw.Abp.AntDesignUI#32]
Create a webapp sample

**Comment by xuzhenlei** [comment]
哥，折腾好好几天，webapp还是跑不起来

**Comment by realLiangshiwei** [comment]
@xuzhenlei 
Check the example and document

https://github.com/realLiangshiwei/Lsw.Abp.AntDesignUI/tree/main/samples/BookStoreWebApp
https://github.com/realLiangshiwei/Lsw.Abp.AntDesignUI/blob/main/README.WebApp.md

**Comment by xuzhenlei** [comment]
谢谢！
