### ISSUE TITLE
請問可以提供 Abp 8.2.2 版本 Blazor Server 的替換過程嗎?

### ISSUE THREAD

**Issue by rainmakerho** [realLiangshiwei/Lsw.Abp.AntDesignUI#34]
您好，
    新增 Abp 8.2.2 Blazor Server 後，要套件 Lsw.Abp.AntDesignUI 要如何進行呢?
    使用 `abp new Acme.BookStore -u blazor-server -m none --theme basic -csf`
 
謝謝您。

**Comment by realLiangshiwei** [comment]
基本上和这个一样，有示例项目你可以看一下。
https://github.com/realLiangshiwei/Lsw.Abp.AntDesignUI/blob/main/README.Blazor.md
