### ISSUE TITLE
Issue while initializing

### ISSUE THREAD

**Issue by RelevanceRo** [realLiangshiwei/Lsw.Abp.AntDesignUI#9]
Hi, there!

I think I followed the install guide correctly, but I am getting this big ass error output in console at init:

![image](https://user-images.githubusercontent.com/53852553/196996124-2d4baa51-e8e5-4273-9bb2-918e2bd0936a.png)

@realLiangshiwei can you offer some insight or tips? 

Blazor Web Assembly App, ABPF 6.0.

Thanks and thank you for the work done! Excellent!

**Comment by realLiangshiwei** [comment]
Please install the latest version,  I will update the document.

![image](https://user-images.githubusercontent.com/16813853/197087817-d4cc184b-e32a-4abc-83c4-d716c4bc252d.png)
